# TripWire Pre-Commit Hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Hook Behavior:
#   - Schema validation (--strict):
#     * CI/CD: Passes if .env missing (correctly not committed)
#     * Pre-commit: Skips .gitignore'd files
#     * Local: Validates .env if present
#   - Secret scanning (--strict):
#     * Skips .gitignore'd files to avoid local dev noise
#     * Scans git history for leaked secrets
#

repos:
  - repo: local
    hooks:
      - id: tripwire-schema-validate
        name: TripWire Schema Validation
        entry: tripwire schema validate --strict
        language: system
        pass_filenames: false
        always_run: true
        description: Validates .env against schema (CI/CD compatible - passes if .env missing)

      - id: tripwire-secret-scan
        name: TripWire Secret Scan
        entry: tripwire security scan --strict
        language: system
        pass_filenames: false
        always_run: true
        description: Scans for secrets in .env and git history (skips .gitignore'd files)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Standard hooks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]
      - id: check-added-large-files
      - id: check-merge-conflict
      # Prevention hooks
      - id: detect-private-key
        exclude: ^tests/
      - id: forbid-submodules
      # Python hooks
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      # JSON Schema hooks for GitHub
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-dependabot
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      # Black hook
      - id: black
        args: [ '--line-length', '120' ]
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "bandit.yaml", "-r"]
        additional_dependencies: ["pbr"]
